# @package _global_
defaults:
  - /runner/default_img

runner:
  checkpointing_steps: 10000
  validation_steps: 50000
  lr_scheduler: constant_with_warmup
  enable_xformers_memory_efficient_attention: true
